### ISSUE TITLE
Handle partial initial state

### ISSUE THREAD

**Issue by olegKusov** [42-px/effector-forms#12]
In official docs there is no example with partial inital state setting.

I try use field.set. It works, but getting type Error.
![telegram-cloud-photo-size-2-5210995898417527044-y](https://user-images.githubusercontent.com/28058268/153844016-91c715ef-0d77-4a0f-a0ba-be4383ba0138.jpg)

The same thing with onChange
![telegram-cloud-photo-size-2-5210995898417527084-y](https://user-images.githubusercontent.com/28058268/153844134-17f9c9dd-d4a6-437c-8fff-04889cf24c4d.jpg)

in createForm I did not use any generic type because did not found it clear how to pass generic type like {name: string, password: string} etc.

**Comment by aanation** [comment]
@olegKusov 

You do not have to manually pass the generic type to createForm. Types are inferred from your form config
