### ISSUE TITLE
Reinit created form's initialValues

### ISSUE THREAD

**Issue by appetiteOlzh** [42-px/effector-forms#16]
Need an event to reinitialize the form. To overwrite the initialValues after receiving them from the back. And set them on form.reset.

**Comment by Muslik** [comment]
You can use setForm:
```javascript
const form = createForm({})

sample({ clock: someEvent, target: form.setForm })
```

**Comment by tplk** [comment]
`setForm` won't reset initial values and dirty state.

**Comment by aanation** [comment]
@appetiteOlzh @tplk 

I added the [setInitialForm](https://github.com/42-px/effector-forms#setinitialform) method that overrides the initial values. That way the isDirty flag becomes false

Please, use v.1.1.0
