### ISSUE TITLE
Add event for adding custom errors manually to many fields

### ISSUE THREAD

**Issue by frkam** [42-px/effector-forms#18]
## Proposal

I propose to add event for adding custom errors manually for many fields

```
sample({
  clock: signUpFx.failData,
  fn: (failData) => {...} // returns [{ field: 'password', rule: 'validation-error', errorText:'Min: 8' }]
  target: signUpForm.fields.addErrors
})
```

## Use case

This event can be used in server-side validation, instead of using example from documentation

```
guard({
  source: loginFx.failData.map(
    (error) => error.name === "already-exists" ? { rule: "already-exists" } : null
  ),
  filter: Boolean,
  target: loginForm.fields.email.addError,
})
```

Related: https://t.me/effector_forms/817

**Comment by aanation** [comment]
@frkam 
Please, try v1.1.0

I added the [form.addErrors](https://github.com/42-px/effector-forms#bulk-errors) event
