### ISSUE TITLE
TypeScript broken

### ISSUE THREAD

**Issue by golovinstan** [42-px/effector-forms#5]
![image](https://user-images.githubusercontent.com/48453440/99413701-1e9c4600-2907-11eb-823e-3a39efa9668f.png)

**Comment by golovinstan** [comment]
![image](https://user-images.githubusercontent.com/48453440/99414331-c1ed5b00-2907-11eb-8650-0170854fb69c.png)

**Comment by aanation** [comment]
@golovinstan 
```form.$values``` it's generic type ```FormValues<T>```. 

Type:
```
brigadeForm.$values.getState().avarRefereeId
```

and check type of avarRefereeId

**Comment by golovinstan** [comment]
combine dont accept brigadeForm.$values.getState()

**Comment by aanation** [comment]
@golovinstan 
Let's take a closer look:
![Screenshot from 2021-01-11 21-08-04](https://user-images.githubusercontent.com/32829122/104192355-4b756100-5451-11eb-9de2-85e05ae7151a.png)


It's generic

**Comment by golovinstan** [comment]
![](https://user-images.githubusercontent.com/48453440/99414331-c1ed5b00-2907-11eb-8650-0170854fb69c.png)

It's not  `
{
  cityId: { 
     init: string; 
     rules: Rule<string, any, any>[]; 
     validateOn: ("change" | "blur")[] 
    }, 
... 
}
`

**Comment by aanation** [comment]
@golovinstan 
Yes, because it's GENERIC of  `{ cityId: { init: string; rules: Rule<string, any, any>[]; validateOn: ("change" | "blur")[] },`
Effecor-forms.

`MyType<AnotherType>` and `AnotherType` are different types.

https://www.typescriptlang.org/docs/handbook/generics.html
