### ISSUE TITLE
No support for effector/ssr

### ISSUE THREAD

**Issue by 0r20** [42-px/effector-forms#6]
I am doing a project on Next.js and effector/ssr. 
After submitting the form, I call the effect like this.

In model:
`export const loginForm = createForm({
    domain: app,
    . . .
});
forward({ from: loginForm.formValidated, to: loginProccesing });
loginProccesing.pending.watch((_) => console.log(_))
`

In component:
`import { useStore } from 'effector-react/ssr';
const isLoading = useStore(loginProccesing.pending);`

Watch store shows that the loginProccesing.pending is changing, but in the case of useStore nothing happens.

**Comment by aanation** [comment]
This feature will be coming very soon. I plan to do it in the next release

**Comment by SQReder** [comment]
bump

**Comment by aanation** [comment]
Please, try the current version (v1.1.0)
