### ISSUE TITLE
resetErrors not trigger formValidated

### ISSUE THREAD

**Issue by Kvodnon** [42-px/effector-forms#9]
Hi!

Case: one of fields must be filled, both empy fields trigger correct  error. But when one of field filled, errors reset visual, but not fact. What could it be? Architecrute screenshot attached.

![image](https://user-images.githubusercontent.com/10090045/142752324-38597082-593a-4342-a3b7-8fd0686dc071.png)

**Comment by Kvodnon** [comment]
formValidated not triggered after resetErrors

**Comment by aanation** [comment]
@Kvodnon 

I don't understand your case. Why do you manually call resetErrors on submit? Why do you manually check the value in the filter? 
Just call submit and subscribe to the formValidated event. The formValidated event will be called if your form is correct and there are no errors
